name: Build y Pruebas

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pytest pylint

      - name: Ejecutar pruebas
        run: pytest test_calculadora.py -v

      - name: Analizar código con Pylint
        run: pylint calculadora.py
